"""
Agent Tool: Explanation Tool

This module defines a LangChain tool wrapper that compiles a comprehensive, structured markdown report
summarizing premium quotes, actuarial explanations, and expected claims projections.
"""

import os
import sys
from langchain_core.tools import tool

# Add parent directory to path to support config/pricing imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from actuarial.mortality import load_raw_table
from actuarial.pricing import calculate_all_pricing
from analytics.insights import generate_pricing_insights, generate_sensitivity_insights
from analytics.sensitivity_analysis import analyze_interest_rate_sensitivity, analyze_mortality_shock_sensitivity
from actuarial.utils import format_currency

@tool
def explanation_tool(age: int, gender: str, term: int, sum_assured: float, interest_rate: float, improvement_rate: float) -> str:
    """
    Generates a structured, text-based actuarial explanation report summarizing 
    premiums, NPV expected claims, and key risk sensitivity insights.
    Useful for questions like 'Write a report for...' or 'Explain the pricing for...'.
    
    Inputs:
      - age (int): Entry age of policyholder
      - gender (str): 'Male' or 'Female'
      - term (int): Policy term in years
      - sum_assured (float): The total claim payout value
      - interest_rate (float): The discount rate in percentage
      - improvement_rate (float): Annual compound mortality improvement
      
    Returns:
      A comprehensive formatted markdown report with actuarial explanations.
    """
    try:
        df_mort = load_raw_table()
        
        # Calculate pricing
        pricing = calculate_all_pricing(
            age=age,
            gender=gender,
            term=term,
            sum_assured=sum_assured,
            interest_rate_pct=interest_rate,
            improvement_rate=improvement_rate,
            df_mort=df_mort
        )
        
        # Calculate sensitivities for insights
        int_sensitivity = analyze_interest_rate_sensitivity(
            age=age,
            gender=gender,
            term=term,
            sum_assured=sum_assured,
            improvement_rate=improvement_rate,
            df_mort=df_mort
        )
        
        shock_sensitivity = analyze_mortality_shock_sensitivity(
            age=age,
            gender=gender,
            term=term,
            sum_assured=sum_assured,
            interest_rate_pct=interest_rate,
            df_mort=df_mort
        )
        
        # Generate insights
        pricing_insights = generate_pricing_insights(pricing)
        sensitivity_insights = generate_sensitivity_insights(int_sensitivity, shock_sensitivity)
        
        # Build Report
        report = (
            f"# ACTUARIAL PRICING & RISK ANALYSIS REPORT\n\n"
            f"**Policyholder Details:**\n"
            f"- Entry Age: {age}\n"
            f"- Gender: {gender}\n"
            f"- Policy Term: {term} Years\n"
            f"- Sum Assured: {format_currency(sum_assured)}\n\n"
            f"**Economic & Mortality Assumptions:**\n"
            f"- Discount Rate: {interest_rate}%\n"
            f"- Mortality Improvement: {improvement_rate*100:.2f}% p.a. compound reduction\n\n"
            f"## 1. Premium Summary Table\n\n"
            f"| Product Type | Net Single Premium (NSP) | Net Level Annual Premium (LAP) | Annuity Due Factor |\n"
            f"| :--- | :---: | :---: | :---: |\n"
            f"| **Term Life** ({term} Years) | {format_currency(pricing['nsp_term'])} | {format_currency(pricing['lap_term'])} / year | {pricing['a_due_term']:.4f} |\n"
            f"| **Whole Life** | {format_currency(pricing['nsp_whole'])} | {format_currency(pricing['lap_whole'])} / year | {pricing['a_due_whole']:.4f} |\n\n"
            f"## 2. Core Actuarial Explanations\n\n"
        )
        
        for insight in pricing_insights:
            report += f"- {insight}\n"
            
        report += "\n## 3. Premium & Risk Sensitivity Analysis\n\n"
        
        for insight in sensitivity_insights:
            report += f"- {insight}\n"
            
        report += (
            f"\n## 4. Expected Claim Distribution (First 5 Years Projection)\n\n"
            f"| Year | Age | Survival Probability (tpx) | Baseline Mortality (qx) | Prob of Death (tpx * qx) | Expected Claims | PV of Claims |\n"
            f"| :---: | :---: | :---: | :---: | :---: | :---: | :---: |\n"
        )
        
        projections = pricing['claims_projection'][:5]
        for proj in projections:
            report += (
                f"| {proj['Year']} | {proj['Age']} | {proj['Survival_Prob_tpx']:.5f} | {proj['Mortality_Prob_qx']:.5f} | "
                f"{proj['Probability_of_Death']:.5f} | {format_currency(proj['Expected_Claim_Amount'])} | {format_currency(proj['PV_Expected_Claim'])} |\n"
            )
            
        report += (
            f"\n---\n*Report generated by the AI-Powered Mortality Improvement Pricing Analyzer.*"
        )
        return report
    except Exception as e:
        return f"Error executing explanation_tool: {str(e)}"
